from transformers import PegasusForConditionalGeneration, PegasusTokenizer
import torch

if __name__ == "__main__":
    paragraph = [
        "WASHINGTON—President Trump had a fever and rapidly dropping blood-oxygen levels on Friday morning, but his condition has since improved, the White House chief of staff said late Saturday, as the administration gave conflicting signals about the president’s condition."
        "Chief of staff Mark Meadows said on Fox News that the president was doing well but wouldn’t be “out of the woods” for another 48 hours. He said he and the president’s doctor had been “very concerned” on Friday morning."
        "Earlier Saturday, in a briefing in front of the Walter Reed National Military Medical Center, Dr. Sean Conley said the president’s symptoms—a mild cough, nasal congestion and fatigue—were improving and that he hadn’t had a fever for 24 hours. But he didn’t give a date for the president’s release and declined to provide a definitive answer on whether Mr. Trump had ever received supplemental oxygen."
        "After Dr. Conley concluded his briefing, a person familiar with the president’s health told reporters that Mr. Trump’s vitals over the past 24 hours were very concerning and that the next 48 hours would be critical. “We’re still not on a clear path to a full recovery,” the person said."
        "The comment was provided to White House reporters in a pool report, attributed to an anonymous source. The Associated Press later attributed the quotes to Mr. Meadows."
        "The White House didn’t confirm that Mr. Meadows made the statement. The Wall Street Journal wasn’t at the briefing."
        "A White House official said the president “was not in great shape Friday,” but said he had “significantly improved today."
        "Mr. Trump on Saturday evening tweeted a video of himself from Walter Reed in which he said he was improving. “I came here, wasn’t feeling so well, I feel much better now, we’re working hard to get me all the way back,” he said, predicting he would be back soon."
        "Still, the president’s hospitalization left his campaign in limbo just a month before the election and cast doubt over efforts to confirm a Supreme Court justice and agree on a new round of stimulus for the coronavirus-stricken economy."
        "In a memo released Saturday night, Dr. Conley said the president had completed his second dose of remdesivir, which is among the few drugs that have been shown to treat Covid-19 and to have been cleared by the Food and Drug Administration for such use. He said the president remained off supplemental oxygen and added: “While not yet out of the woods, the team remains cautiously optimistic.”"
        "The confusion about the state of the president’s health arose as a cascading list of aides and allies revealed positive test results. The president’s test followed reports that top aide Hope Hicks tested positive. In the following days many people have reported positive tests after attending a Rose Garden ceremony last Saturday at which Mr. Trump announced his Supreme Court nominee, which featured close seating and few people wearing masks."
        "White House officials said the president’s diagnosis wouldn’t affect his governing. White House communications director Alyssa Farah said there would be no transfer of power with the president’s move to Walter Reed."
        "The president’s personal attorney Rudy Giuliani said in an interview that he spoke to the president Saturday afternoon. “He doesn’t sound like he’s sick,” Mr. Giuliani said."
        "He also said Mr. Trump dictated a lengthy message to disseminate, which said his diagnosis “can be a very good thing in the sense that people can see that you can contract this disease and you can get through it.” He said Mr. Trump told him that as president, “He couldn’t just hide out in the White House for five months…A general doesn’t lead an army from behind.”"
        "Mr. Giuliani said he told the president that there was some confusion over his condition but that Mr. Trump didn’t appear aware of the conflicting public messages. Mr. Trump said that he felt fine but that doctors had advised him to stay at the hospital because “this disease can have strange developments,” Mr. Giuliani said."
        "Senate Majority Leader Mitch McConnell tweeted Saturday that he had spoken with the president about confirming the Supreme Court nominee, Judge Amy Coney Barrett, among other matters. “He sounds well and says he’s feeling good,” Mr. McConnell wrote."
        "Republicans are trying to get Judge Barrett confirmed by Election Day. Democrats called for postponing her confirmation, arguing that it could be difficult to hold in-person hearings as some senators are diagnosed with the virus."
        "As Mr. Trump canceled trips to Florida and Wisconsin, it remained unclear when—or if—the president would be able to return to the campaign trail and whether he would be able to participate in the remaining two debates with Democratic rival Joe Biden. Mr. Biden on Friday tested negative for the virus, his campaign said."
        "Vice President Mike Pence, who has tested negative twice in the past two days and hasn’t quarantined on the advice of his doctor, will hold a campaign event in Arizona on Thursday. The campaign said Saturday it would host virtual events until the vice presidential debate Oct. 7 but would resume in-person events after that with Mr. Pence and members of the president’s family."
        "There was confusion about when the White House learned of the president’s exposure and subsequent positive test. Dr. Conley declined to give a date for when Mr. Trump last tested negative, and he referred to the president as being 72 hours into his diagnosis, which would put the date of his positive test on Wednesday. A White House official later said Dr. Conley meant to say it was the third day since the president was diagnosed Thursday night, not that 72 hours had passed since his diagnosis."
        "In a memo hours after his briefing concluded Saturday, Dr. Conley said the president had been diagnosed on the evening of Oct. 1, which was Thursday."
        "On whether the president had ever received oxygen, Dr. Conley said: “Thursday no oxygen, none at this moment, and yesterday with the team while we were all here, he was not on oxygen.”"
        "The growing list of positive tests among the president’s contacts included former White House adviser Kellyanne Conway, Republican Sens. Mike Lee of Utah and Thom Tillis of North Carolina and the Rev. John Jenkins, the president of the University of Notre Dame, all of whom attended the event in the Rose Garden."
        "The president’s campaign manager, Bill Stepien, who was with the president for debate preparation last weekend and at the first presidential debate in Cleveland, also tested positive, as did former New Jersey Gov. Chris Christie, who helped the president prepare for Tuesday’s debate. Mr. Stepien was experiencing mild symptoms and plans to quarantine until he recovers, the campaign said."
        "Mr. Giuliani said he and Mr. Trump discussed Mr. Christie, and “we both agreed we were the most worried about him” among all of their associates who had tested positive. Mr. Giuliani said he tested negative Friday after being “sandwiched” between Mr. Christie and Ms. Conway during debate preparation sessions over the past week. Mr. Christie tweeted Saturday that he was checking himself into a hospital as a precautionary measure, citing his history of asthma."
        "Other White House and campaign aides reported negative tests, and some were awaiting results. Republican National Committee Chairwoman Ronna McDaniel tested positive earlier this week, the GOP said. Wisconsin Republican Sen. Ron Johnson tested positive Friday, his spokesman said. Mr. Johnson is the third senator this week to test positive for the virus."
        "The diagnoses exposed severe holes in the White House’s Covid-19 protocol, which has largely consisted of frequent rapid tests. Health experts say that conducting frequent tests without also wearing masks and social distancing is an ineffective way of combating the virus, since it can take days for a person to test positive after being infected."
        "The White House will continue to make mask-wearing optional on its grounds, an official said Friday."
        "While many Covid-19 patients recover without suffering serious illness, Mr. Trump’s age of 74 puts him at higher risk from the virus, as does his obesity. According to the CDC, people in their 60s and 70s are “at higher risk for severe illness than people in their 50s.”"
        "If the president’s condition were to worsen, he could temporarily transfer power to Mr. Pence under the 25th Amendment. Such a transfer has happened only three times in U.S. history, when Presidents Reagan and George W. Bush underwent colonoscopies, though Mr. Reagan said at the time that he wasn’t formally invoking the amendment. In other incidents, such as when Mr. Reagan was shot and had to undergo emergency surgery in 1981, power wasn’t formally transferred.",
        "WASHINGTON—Doctors said President Trump’s condition was improving on Sunday, two days after he checked into the hospital, though they also noted that his blood oxygen level had dropped on Saturday and that he was taking a steroid that has typically been given to Covid-19 patients who are seriously ill."
        "Doctors said on Sunday the president could be sent back to the White House as soon as Monday, as they sought to clarify his condition after several days of contradictory information from doctors and advisers. Dr. Sean Conley, the president’s physician, said at a news conference on Sunday at Walter Reed National Military Medical Center that Mr. Trump’s condition “continues to improve.” But he also said Mr. Trump’s symptoms had been serious, adding that he tried to provide an “upbeat” assessment in a Saturday briefing."
        "Dr. Conley said the president experienced two drops in oxygen saturation levels. Late Friday morning, before he was admitted to the hospital, it dropped below 94%, and he was given supplemental oxygen for about an hour. He experienced a high fever at the time, Dr. Conley said, without specifying his temperature. The 74-year-old president’s oxygen level also dropped on Saturday, this time to about 93%, his physicians said."
        "A mildly obese patient of Mr. Trump’s age with oxygen saturation below 94% would typically be given supplemental oxygen for a half or full day and would be monitored to see if levels return to normal, said Peter Chin-Hong, an infectious-disease specialist and professor of medicine at the University of California San Francisco. Normal blood oxygen saturation levels range between 95% and 100%."
        "Dr. Conley didn’t offer a clear answer when pressed about whether Mr. Trump required supplemental oxygen on Saturday, saying: “I’d have to check with the nursing staff. I don’t think—if he did, it was very limited.” He also declined to elaborate on what the doctors’ examinations of the president’s lungs had found. The White House didn’t respond to follow-up inquiries."
        "Raising additional questions about Mr. Trump’s condition, the president’s doctors said he had been treated with dexamethasone. The generic drug is a commonly used steroid that has been shown to help severely ill Covid-19 patients. The World Health Organization issued updated guidelines last month recommending steroid treatment in patients with severe or critical Covid-19, including patients with difficulty breathing and those requiring oxygen support with a ventilator or face mask. The WHO recommended not to use steroids in treating patients with nonsevere Covid-19."
        "Mr. Trump also has also taken Regeneron Pharmaceuticals Inc.’s experimental antibody drug cocktail, and he is currently on a five-day course of the antiviral drug remdesivir, which has been authorized for treatment of hospitalized Covid-19 patients."
        "Doctors also said Sunday that the president’s vital signs were stable, he wasn’t experiencing shortness of breath, and he has been fever-free since Friday."
        "Mr. Trump, in a video message posted to Twitter on Sunday evening, said he would make a “little surprise visit” to his supporters gathered outside Walter Reed. “I learned a lot about Covid. I learned it by really going to school. This is the real school. This isn’t the let’s-read-the-books school. And I get it and I understand it,” he said on the video."
        "Shortly after the message was posted to Twitter, videos posted online showed Mr. Trump, wearing a black mask, riding in the back of an SUV and waving to supporters gathered outside the hospital."
        "“President Trump took a short, last-minute motorcade ride to wave to his supporters outside and has now returned to the Presidential Suite inside Walter Reed,” White House spokesman Judd Deere said."
        "Asked Sunday why he didn’t offer the more serious details about the president’s condition the day before, Dr. Conley said: “I was trying to reflect the upbeat attitude that the team, that the president, through this course of illness, has had. I didn’t want to give any information that would steer the course of illness in another direction and in doing so it came off that we were trying to hide something, which wasn’t necessarily true.”"
        "An email went out to White House staff Sunday evening, telling staffers to stay home if they are experiencing Covid-19 symptoms, said a person familiar with the email. The email said, “If you or your colleagues feel you should be practicing telework or have questions about your ability to do so, please contact your supervisor.”"
        "Mr. Trump’s Covid-19 diagnosis might complicate the process of confirming a new Supreme Court nominee and by taking the GOP president off the trail has further scrambled the presidential campaign with just 30 days until Election Day. It also has generated fresh anxiety about the virus that to date has claimed about 209,000 lives in the U.S. White House officials and the president’s supporters have said Mr. Trump continues to conduct his presidential duties, despite his illness."
        "Democratic presidential nominee Joe Biden was tested for Covid-19 Sunday and was negative, his campaign said."
        "Mr. Trump addressed the public in a four-minute video posted to Twitter on Saturday, saying he was feeling much better and added that he wants to recover quickly so he can finish the presidential campaign. The president said he had no choice but to be out in public during the pandemic, explaining that he was willing to take the risk of contracting the coronavirus to continue leading the country. “I can’t be locked up in a room upstairs,” he said."
        "Mr. Trump tweeted from Walter Reed Sunday afternoon: “I really appreciate all of the fans and supporters outside of the hospital. The fact is, they really love our Country and are seeing how we are MAKING IT GREATER THAN EVER BEFORE!”"
        "White House aides said Mr. Trump was continuing to work. “I spoke with the President. President Trump is fully engaged and fully in charge,” White House press secretary Kayleigh McEnany wrote in an email. The president was scheduled to receive a national-security briefing from Walter Reed on Sunday, officials said. The White House also distributed photographs that it said showed Mr. Trump working from Walter Reed."
        "Asked what the president’s treatment might look like at the White House, communications director Alyssa Farah said Sunday that there was a “fully operating medical team” at the White House, saying, “There’s a lot we can do from the White House, the residence.”"
        "White House national-security adviser Robert O’Brien said Sunday that the administration isn’t taking steps to transfer power to Vice President Mike Pence. “No, that’s not something that’s on the table at this point,” he said on CBS News. He added later, “I’m not going to address hypotheticals, but we have plans for everything.” Mr. O’Brien said wearing masks is now mandatory in the West Wing. It had previously been voluntary throughout the pandemic."
        "Mr. O’Brien also warned against any attempt by U.S. rivals to take advantage of a situation that security experts said presents a fertile ground for interference and disinformation. “I think our adversaries know that the United States government is steady at the tiller and that we’re protecting the American people,” he said."
        "The president and his senior advisers sought to keep a close hold on the early positive test results among White House staff, and some in the Trump administration have privately expressed frustration that information hasn’t been shared more widely. Mr. Trump didn’t disclose a positive result from a rapid test for Covid-19 on Thursday while awaiting the findings from a more thorough coronavirus screening, according to people familiar with the matter. He was admitted to Walter Reed on Friday."
        "If the president’s condition were to worsen, he could temporarily transfer power to Mr. Pence under the 25th Amendment, which was ratified in 1967. Such a transfer has happened only three times in U.S. history, when then-presidents Ronald Reagan and George W. Bush underwent colonoscopies. Power wasn’t formally transferred when Mr. Reagan was shot and had to undergo emergency surgery in 1981."
        "House Speaker Nancy Pelosi (D., Calif.), who is second in line for the presidency, said Sunday on “Face the Nation” that she was receiving her information on the president’s health from the media, not through any formal briefings."
        "On Sunday, Trump campaign aide Jason Miller said on NBC’s “Meet the Press” that he had spoken with the president Saturday, describing him in “very good spirits.”"
        "“The president said a couple of things,” said Mr. Miller. “Number one, that he’s going to defeat this virus, that as a nation we’re going to defeat this virus and our campaign is going to defeat this virus.”"
        "As Mr. Trump canceled trips to Florida and Wisconsin, it remained unclear when—or if—he would be able to return to the campaign trail and whether he would be able to participate in the remaining two debates with his Democratic rival."
        "Mr. Biden led the president, 53% to 39%, among registered voters in a new Wall Street Journal/NBC News poll, which was conducted in the two days after the debate but before news emerged that Mr. Trump had tested positive for Covid-19. Mr. Biden’s 14-point lead compared with an 8-point advantage last month."
        "Mr. Pence was expected to remain at the U.S. Naval Observatory, his northwest Washington, D.C., residence, until he departs on Monday for Salt Lake City, where he will participate in the vice presidential debate on Wednesday. After the debate, he is scheduled to continue on to Arizona for a campaign rally. The Trump campaign said attendees would be provided with masks that they are encouraged to wear and undergo temperature checks."
        "At least eight people who were in proximity to Mr. Trump over the past week have tested positive for Covid-19, the disease caused by the coronavirus, including first lady Melania Trump, former senior White House adviser Kellyanne Conway, Trump campaign manager Bill Stepien and former New Jersey Gov. Chris Christie. Mr. Christie checked himself into a hospital on Saturday as a precaution, citing increased risk from the virus as a result of his asthma."
        "A spokeswoman for the first lady said Saturday that she was doing well and her symptoms haven’t worsened."
        "Republican Sens. Mike Lee of Utah, Thom Tillis of North Carolina and Ron Johnson of Wisconsin, as well as Republican National Committee Chairwoman Ronna McDaniel and the Rev. John Jenkins, the president of the University of Notre Dame, also tested positive. Many of those who tested positive attended a Rose Garden ceremony last Saturday where Mr. Trump announced his Supreme Court nominee. The event featured little social distancing or mask usage."
    ]
    model_name = 'google/pegasus-billsum'
    torch_device = 'cuda' if torch.cuda.is_available() else 'cpu'

    tokenizer = PegasusTokenizer.from_pretrained(model_name)
    model = PegasusForConditionalGeneration.from_pretrained(model_name).to(torch_device)
    batch = tokenizer.prepare_seq2seq_batch(paragraph, truncation=True, padding='longest').to(torch_device)
    translated = model.generate(**batch)
    tgt_text = tokenizer.batch_decode(translated, skip_special_tokens=True)


    print(paragraph)
    print(tgt_text)
    print(tokenizer.vocab_size)
